### ISSUE TITLE
o select * (get all) ta parado no tempo

### ISSUE THREAD

**Issue by CodyKoInABox** [bonsite/bonsite#13]
eu fiquei 2 horas ontem de madrugada tentando resolver isso sem sucesso nenhum, entao vai ficar assim, a menos que algum de voces descubra o problema.

nao sei se quando voces estiverem lendo isso o branch ainda vai estar separado, ou se ja vou ter dado merge, mas por enquanto to trabalhando na branch chamada "new-database-testing-frontend".

Eu tenho 3 endpoints:
- GET ALL (select em todos os bonsais)
- GET BY ID (select no bonsai com o ID informado)
- POST (cria um bonsai)
- 
o problema é: O GET ALL tá parado no tempo, desde a primeira vez que eu rodei ele, o resultado é sempre o mesmo.
Vamos lá, eu rodo GET ALL, tudo certo, ai vou no post e crio um bonsai novo, se eu volto no GET ALL, o bonsai novo nao aparece, mas se eu tento dar um GET BY ID usando o ID desse bonsai que eu acabei de criar, ELE FUNCIONA!! Só o GET ALL que não funciona, não importa quantos bonsais novos eu crie.

Já tentei de tudo, reescrevi boa parte do código, mudei um monte de config, entrei direto na DB e dei um SELECT * from bonsai, que funcionou perfeito. Só o endpoint do /get/all que nao funciona.

Quinta posso explicar pessoalmente pra voces, mas ja perdi muito tempo tentando resolver entao vou deixar assim.

**Comment by CodyKoInABox** [comment]
Sim, já reiniciei o next, muitas vezes. Já limpei o cache de TUDO. Já reescrevi o código. Já botei pra ele nao salvar nada no cache. Já olhei direto na database e vi que lá funciona.

**Comment by CodyKoInABox** [comment]
**Banco de dados na neon.tech:**
![image](https://github.com/user-attachments/assets/bbbb89f9-352f-4bb2-8b8a-2cb6783cc699)

----------

**Resultado do /get/all:**
![image](https://github.com/user-attachments/assets/4f6ce7ec-3a41-4f29-a6fb-4647ce61e95c)

----------

**Resultado do /get/id/500:** _(um dos novos bonsais que nao aparecem no /get/all)_
![image](https://github.com/user-attachments/assets/803711eb-1202-4bda-98fc-f63a464a9ada)

**Comment by icrcode** [comment]
@VictorMatheusMoreira ta ai um quest pra ti!!!

**Comment by icrcode** [comment]
Resolvi!

**Comment by CodyKoInABox** [comment]
resolveu nada fui eu

**Comment by CodyKoInABox** [comment]
Resolvi!
